export const DEFAULT_BUSINESS_CATEGORIES: string[] = [
  "Accounting",
  "Airlines/Aviation",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation",
  "Apparel/Fashion",
  "Architecture/Planning",
  "Arts/Crafts",
  "Automotive",
  "Banking/Mortgage",
  "Biotechnology/Greentech",
  "Broadcast Media",
  "Building Materials",
  "Chemicals",
  "Computer Hardware",
  "Computer Software",
  "Construction",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Education / E-learning",
  "Electrical / Electronic Manufacturing",
  "Entertainment",
  "Farming / Agriculture",
  "Financial Services",
  "Food & Beverages",
  "Government Administration",
  "Healthcare / Hospital",
  "Hospitality / Tourism",
  "Information Technology",
  "Insurance",
  "Legal Services",
  "Logistics / Supply Chain",
  "Manufacturing",
  "Marketing / Advertising",
  "Mining / Metals",
  "Real Estate",
  "Retail / E-commerce",
  "Security / Investigations",
  "Telecommunications",
  "Textiles",
  "Transportation",
  "Utilities",
  "Wholesale / Distribution",
];

export const INDIAN_STATES: string[] = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];
